apiVersion: v1
kind: ConfigMap
metadata:
  name: haruum-outlet-config
data:
  outlet_url: haruum-outlet-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haruum-outlet-deployment
  labels:
    app: haruum-outlet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haruum-outlet
  template:
    metadata:
      labels:
        app: haruum-outlet
    spec:
      containers:
        - name: haruum-outlet
          image: johaneschristiancc/cc_haruum_outlet:latest
          imagePullPolicy: IfNotPresent
          ports:
            - protocol: TCP
              containerPort: 80
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongodb-config-map
                  key: db_url
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DBNAME
              value: "haruum_nosql"
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef: 
                  name: mongodb-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: haruum-outlet-service
spec:
  selector:
    app: haruum-outlet
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80